version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=Cycling
      - MYSQL_ROOT_PASSWORD=dummyp@ssword45
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
